name: CI-CD

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  tests:

    name: .NET ${{ matrix.dotnet }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      fail-fast: true

      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dotnet: [ '6.0' ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Dependencies
        run: dotnet restore

      - name: Build
        run: make build-ci

      - name: Tests
        run: make test-ci

  deploy:
    needs: tests

    name: Deploy into production branch

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Merge main into prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: prod
          github_token: ${{ github.token }}